apiVersion: v1
kind: Secret
metadata:
  name: payments-api-secret
type: Opaque
stringData:
  connection-string: "Data Source=/app/data/payments.db"
  rabbitmq-username: "guest"
  rabbitmq-password: "guest"
